# Generated by Django 3.2.7 on 2021-12-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pat', models.CharField(max_length=7)),
            ],
        ),
    ]
